version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: IFood
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  app:
    image: next-prisma-docker
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: build
    depends_on:
      - postgres
    env_file:
      - dev.env
    ports:
      - 3000:3000

volumes:
  postgres_data:
